def @arguementError()
    final error_name, error_message = "ARGUEMENT_ERROR", "Missing arguement, '{0}' is required".format(['name'])
    let error = RuntimeError(error_name, error_message)
    raise error
end

def @keyError()
    final error_name, error_message = f"KEY_ERROR", "Missing key, '{0}' is required".format(['name'])
    let error = KeyError(error_name, error_message)
    raise error
end

def @typeError()
    final error_name, error_message = "TYPE_ERROR", "Invalid type, '{0}' is required".format(['#'])
    let error = TypeError(error_name, error_message)
    raise error
end

def @attemptCatch(func)
    attempt:
        func()
    catch Exception as e:
        println(f"Exception: %{e}")
    catch KeyboardInterrupt as e:
        println(f"KeyboardInterrupt: %{e}")
    catch:
        println("Unknown error")
    end
end

def @main()
    while true:
        println("Hello")
    end 
end



attempt:
    println(Test(''))
catch Exception as e:
    println(f"Exception: %{e}")
finally:
    println("an error occured")
end
